### ISSUE TITLE
v20 nodes are not shown

### ISSUE THREAD

**Issue by cjdelisle** [zielmicha/fc00.org#20]
This filter: https://github.com/zielmicha/fc00.org/blob/master/web/graph.py#L45
is dropping v20 nodes and there are now few of them.

**Comment by progval** [comment]
@zielmicha ping

**Comment by zielmicha** [comment]
Should be fixed now.

**Comment by progval** [comment]
It's not, I don't see my node on https://www.fc00.org/

**Comment by zielmicha** [comment]
I think that actually no one sent any v20 nodes before... I've upgraded CJDNS running on fc00.org to v20 and now I can see some v20 nodes.

**Comment by byaeger** [comment]
This issue is not fixed. I added my node (h.byaeger.us) to the nodedb/nodes file and still to this day cant see it on fc00.org. By the way h.fc00.org is down.

**Comment by progval** [comment]
@byaeger My node (helium.hype.progval.net) is shown. Are you sure your node is connected to hyperboria (eg. check you can connect to fc00's IRC server)?

**Comment by byaeger** [comment]
No it's not connected to hyperboria, I didn't know it mattered. I have to change the Ipv6. I'll change it and see from there. Thanks @ProgVal

**Comment by byaeger** [comment]
My node is now shown on fc00! Thanks @ProgVal for helping!
